export const productsSecondCategory = [
  {
    id: 1,
    image: 'https://images-na.ssl-images-amazon.com/images/I/718NVofDrCL._AC_SL1500_.jpg',
    name: 'iOttie Easy One Touch 4 Dash & Windshield Car Mount Phone Holder Desk Stand Pad & Mat for iPhone, Samsung, Moto, Huawei, Nokia, LG, Smartphones',
    price: 799,
    description: 'Easy One Touch Lock/Release: Patented easy one touch mechanism allows quick one hand open and close operation Adjustable Viewing: The newly re-designed telescopic arm extends from 4 – 6.5 inch and pivots on 225 degree arc for a variety of optimal positions',
    rating: 3.8,
    link: 'https://www.amazon.com/iOttie-Dashboard-Windshield-Samsung-Smartphone/dp/B076B27WP6/ref=sr_1_1?dchild=1&qid=1614711781&s=electronics&sr=1-1',
  },
  {
    id: 2,
    image: 'https://images-na.ssl-images-amazon.com/images/I/61hy2h8nvlL._AC_SL1200_.jpg',
    name: 'AUKEY Car Phone Mount 360 Degree Rotation Dashboard Windshield [Strong Magnetic] Cell Phone Holder for Car Compatible with iPhone 11 Pro/11/XS Max/XS/8/7 and More',
    price: 799,
    description: 'Best Viewing:The base is able to rotate through 360 degrees, and the adjustable arm and ball joint makes it easy to find the ideal phone viewing angle',
    rating: 3.8,
    link: 'https://www.amazon.com/AUKEY-Rotation-Dashboard-Magnetic-Compatible/dp/B07YCF3GGY/ref=sr_1_3?dchild=1&qid=1614725201&s=electronics&sr=1-3',
  },
  {
    id: 3,
    image: 'https://images-na.ssl-images-amazon.com/images/I/713fujBvS9L._AC_SL1500_.jpg',
    name: 'Roam Universal Premium Bike Phone Mount for Motorcycle - Bike Handlebars, Adjustable, Fits iPhone 12, 12Pro 11, X, XR, 8 | 8 Plus, 7 | 7 Plus | Galaxy, S10,...',
    price: 799,
    description: 'UNIVERSAL FOR ALL PHONES: This universal bike phone mount will securely fit almost any cell phone up to 3.5 inches wide! Holds iPhone X, iPhone XR, iPhone 8 | 8Plus, iPhone 7 | 7 Plus, iPhone 6 | 6s | 6 Plus. Samsung Galaxy S7 | Galaxy S7 Edge, Galaxy S9, OnePlus 3, HTC 11. Refer to SIZING GUIDE in the description for more.',
    rating: 3.8,
    link: 'https://www.amazon.com/Roam-Universal-Premium-Phone-Motorcycle/dp/B01LWDCSIZ/ref=sr_1_16?dchild=1&qid=1614725201&s=electronics&sr=1-16',
  }, {
    id: 4,
    image: 'https://images-na.ssl-images-amazon.com/images/I/71C4tTMoBnL._AC_SL1500_.jpg',
    name: 'Dash Cam Front and Rear CHORTAU Dual Dash Cam 3 inch Dashboard Camera Full HD 170° Wide Angle Backup Camera with Night Vision WDR G-Sensor Parking Monitor Loop Recording Motion Detection',
    price: 799,
    description: '★【Dash Cam Front and Rear】This dual dash cam equipped with 1080P resolution front camera and waterproof rear camera.The car dashcam with 6 pcs IR LED and Wide Dynamic Range, the front camera captures the license plates and road signs clearly even at night, thus ensuring to get you the best footage. Wide-angle front (170°) and rear（130°）camera help eliminate the blind spots of your vision. ',
    rating: 3.8,
    link: 'https://www.amazon.com/CHORTAU-Dashboard-G-Sensor-Recording-Detection/dp/B07Q5R22DV/ref=sr_1_9?dchild=1&qid=1614725201&s=electronics&sr=1-9',
  },
   {
    id: 5,
    image: 'https://images-na.ssl-images-amazon.com/images/I/71uCMcguXPL._AC_SL1500_.jpg',
    name: 'APEMAN Mini Dash Cam 1080P Car Camera Driving Recorder Night Vision, 170° Wide Angle, Motion Detection, Parking Monitoring, G-Sensor, Loop Recording',
    price: 799,
    description: 'Self Development & Brand New Design - C420 continues the lightweight, mini design of the previous version; it can be perfectly hidden behind the rear mirror. The appearance, texture and the upgrade of the button make the product feel more comfortable; the operation is still simple and friendly to new users.',
    rating: 3.8,
    link: 'https://www.amazon.com/APEMAN-Recorder-Detection-G-Sensor-Recording/dp/B07GFF7NLB/ref=sr_1_50?dchild=1&qid=1614725430&s=electronics&sr=1-50',
  },

];