export const productsFourthCategory = [
  {
    id: 1,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81ti8lPxEjL._AC_SL1500_.jpg',
    name: 'SanDisk 128GB Ultra MicroSDXC UHS-I Memory Card with Adapter - 120MB/s, C10, U1, Full HD, A1, Micro SD Card - SDSQUA4-128G-GN6MA',
    price: 799,
    description: 'Ideal for Android smartphones and tablets, and MIL cameras Up to 128GB to store even more hours of Full HD video (2). 1GB=1,000,000,000 bytes. 1TB=1,000,000,000,000 bytes. Actual user storage less. (2) Full HD (1920x1080) video support may vary based upon host device, file attributes, and other factors. See official SanDisk website.',
    rating: 3.8,
    link: 'https://www.amazon.com/SanDisk-128GB-MicroSDXC-Memory-Adapter/dp/B08GYKNCCP/ref=sr_1_1?dchild=1&qid=1614711768&s=electronics&sr=1-1',
  },
  {
    id: 2,
    image: 'https://images-na.ssl-images-amazon.com/images/I/61pBvlYVPxL._AC_SL1500_.jpg',
    name: 'Amazon Basics High-Speed 4K HDMI Cable - 6 Feet',
    price: 799,
    description: 'HDMI A Male to A Male Cable: Supports Ethernet, 3D, 4K video and Audio Return Channel (ARC) Connects Blu-ray players, Fire TV, Apple TV, PS4, PS3, XBox One, Xbox 360, computers and other HDMI-enabled devices to TVs, displays, A/V receivers and more',
    rating: 3.8,
    link: 'https://www.amazon.com/AmazonBasics-High-Speed-HDMI-Cable-1-Pack/dp/B014I8SSD0/ref=sr_1_2?dchild=1&qid=1614713828&s=electronics&sr=1-2',
  },
  {
    id: 3,
    image: 'https://images-na.ssl-images-amazon.com/images/I/61wKZ4noXaL._AC_SL1024_.jpg',
    name: 'Samsung Electronics EVO Select 256GB MicroSDXC UHS-I U3 100MB/s Full HD & 4K UHD Memory Card with Adapter (MB-ME256HA)',
    price: 799,
    description: 'Ideal for Recording 4K UHD Video: Samsung micro SD EVO Select is perfect for high res photos, gaming, music, tablets, laptops, action cameras, DSLRs, drones, smartphones (Galaxy S20 5G, S20+ 5G, S20 Ultra 5G, S10, S10+, S10e, S9, S9+, Note9, S8, S8+, Note8, S7, S7 Edge, etc. ), Android devices and more',
    rating: 3.8,
    link: 'https://www.amazon.com/Samsung-Electronics-microSDXC-Adapter-MB-ME256HA/dp/B0887P21Z2/ref=sr_1_4?dchild=1&qid=1614713828&s=electronics&sr=1-4',
  }, {
    id: 4,
    image: 'https://images-na.ssl-images-amazon.com/images/I/71C2W%2BbBW6L._AC_SL1500_.jpg',
    name: 'DJI Mavic Air 2 Fly More Combo - Drone Quadcopter UAV with 48MP Camera 4K Video 8K Hyperlapse 1/2" CMOS Sensor 3-Axis Gimbal 34min Flight Time ActiveTrack 3.0 Ocusync 2.0, Gray',
    price: 799,
    description: '【UP YOUR GAME】: The Mavic Air 2 camera drone takes power and portability to the next level. It combines a powerful camera with intelligent shooting modes for stunning results. Push your imagination to its limits because aerial photography has never been this easy.',
    rating: 3.8,
    link: 'https://www.amazon.com/DJI-Mavic-Air-More-Combo/dp/B086XCGMN7/ref=sr_1_9?dchild=1&qid=1614713828&s=electronics&sr=1-9',
  },
   {
    id: 5,
    image: 'https://images-na.ssl-images-amazon.com/images/I/71f8wMHfklL._AC_SL1500_.jpg',
    name: 'GoPro HERO9 Black - Waterproof Action Camera with Front LCD and Touch Rear Screens, 5K Ultra HD Video, 20MP Photos, 1080p Live Streaming, Webcam, Stabilization',
    price: 799,
    description: '5K Video - Shoot stunning video with up to 5K resolution, perfect for maintaining detail even when zooming in 20MP Photo with SuperPhoto: Capture crisp, pro-quality photos with 20MP clarity. And with SuperPhoto, HERO9 Black can automatically pick all the best image processing for you',
    rating: 3.8,
    link: 'https://www.amazon.com/GoPro-HERO9-Black-Waterproof-Stabilization/dp/B08DK5ZH44/ref=sr_1_22?dchild=1&qid=1614713828&s=electronics&sr=1-22',
  },
];